name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build
    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: .next

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Debug SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.HOST }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh-keygen -l -f private_key
        ssh -v -i private_key -o StrictHostKeyChecking=no sp-deploy@$HOST echo "Connection test"

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: github-deploy
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        debug: true
        script: |
          cd /opt/myth/app/myth
          GIT_SSH_COMMAND='ssh -i /home/sp-deploy/.ssh/sp-prod-key -o IdentitiesOnly=yes' git pull origin main
          /opt/myth/scripts/deploy.sh

      